site_name: "Kibana 5.2 中文文档"
site_url: http://kibana.apachecn.org
site_description: "Kibana 5.2 中文文档"
site_author: ApacheCN Team

repo_url: https://github.com/apachecn/kibana-doc-zh
repo_name: kibana-doc-zh

use_directory_urls: true
nav:
- "Kibana 5.2 中文文档" : "README.md"
- "介绍" : "0.md"
- "设置" : "1.md"
- "安装 Kibana" : "2.md"
- "使用 .tar.gz 的方式安装 Kibana" : "3.md"
- "使用 Debian Package 的方式安装 Kibana" : "4.md"
- "使用 RPM 的方式安装 Kibana" : "5.md"
- "Windows 上安装 Kibana" : "6.md"
- "配置 Kibana" : "7.md"
- "Docker 上运行 Kibana" : "8.md"
- "获取镜像" : "9.md"
- "Docker 上配置 Kibana" : "10.md"
- "访问 Kibana" : "11.md"
- "关联 Kibana 与 kibana" : "12.md"
- "与 Tribe nodes 一起使用 Kibana" : "13.md"
- "在生产环境中使用 Kibana" : "14.md"
- "升级 Kibana" : "15.md"
- "标准升级" : "16.md"
- "标准升级与 Reindex（重建索引）" : "17.md"
- "新安装" : "18.md"
- "重大改变" : "19.md"
- "5.0 中的重大改变" : "20.md"
- "入门指南" : "21.md"
- "加载样本数据" : "22.md"
- "定义 index pattern（索引模式）" : "23.md"
- "Discover（发现）数据" : "24.md"
- "Visualizing（可视化）数据" : "25.md"
- "将它们全部放入 Dashboard（仪表盘）" : "26.md"
- "总结" : "27.md"
- "Discover（发现）" : "28.md"
- "设置时间过滤器" : "29.md"
- "搜索数据" : "30.md"
- "字段过滤器" : "31.md"
- "查看文档数据" : "32.md"
- "查看字段数据的统计信息" : "33.md"
- "Visualize（可视化）" : "34.md"
- "创建可视化" : "35.md"
- "Area Charts（面积图）" : "36.md"
- "Data Table（数据表）" : "37.md"
- "Line Charts（折线图）" : "38.md"
- "Markdown Widget（小部件）" : "39.md"
- "Metric（度量）" : "40.md"
- "Pie Charts（饼图）" : "41.md"
- "Tile Maps（平铺地图）" : "42.md"
- "Vertical Bar Charts（垂直条形图）" : "43.md"
- "Tag Clouds（标签云）" : "44.md"
- "Heatmap Chart（热力图）" : "45.md"
- "Dashboard（仪表盘）" : "46.md"
- "构建仪表盘" : "47.md"
- "加载仪表板" : "48.md"
- "分享仪表盘" : "49.md"
- "Timelion" : "50.md"
- "创建时间序列可视化" : "51.md"
- "Console（控制台）" : "52.md"
- "多请求支持" : "53.md"
- "自动格式化" : "54.md"
- "键盘快捷键" : "55.md"
- "历史" : "56.md"
- "控制台设置" : "57.md"
- "配置控制台" : "58.md"
- "安全控制台" : "59.md"
- "Management（管理）" : "60.md"
- "Index Pattern（索引模式）" : "61.md"
- "Managing Fields（管理字段）" : "62.md"
- "String Field Formatters（字符串字段格式化程序）" : "63.md"
- "Date Field Formatters（日期字段格式化程序）" : "64.md"
- "Geographic Point Field Formatters（地理点字段格式化程序）" : "65.md"
- "Numeric Field Formatters（数值字段格式化）" : "66.md"
- "Scripted Fields（脚本字段）" : "67.md"
- "设置高级选项" : "68.md"
- "管理保存的搜索，可视化和仪表盘" : "69.md"
- "Kibana 插件" : "70.md"
- "安装插件" : "71.md"
- "更新和删除插件" : "72.md"
- "禁用插件" : "73.md"
- "配置插件管理器" : "74.md"
- "已知插件" : "75.md"
- "版本说明" : "76.md"
- "5.2.2 版本说明" : "77.md"
- "5.2.1 版本说明" : "78.md"
- "5.2.0 版本说明" : "79.md"
- "5.1.2 版本说明" : "80.md"
- "5.1.1 版本说明" : "81.md"
- "5.1.0 版本说明" : "82.md"
- "5.0.2 版本说明" : "83.md"
- "5.0.1 版本说明" : "84.md"
- "5.0.0 版本说明" : "85.md"

theme:
  name: mkdocs
  custom_dir: 'custom_theme/'
  
  # 404 page
  static_templates:
    - 404.md
  
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  
  # Default values, taken from mkdocs_theme.yml
  language: 'zh'
  feature:
    tabs: false
  palette:
    primary: 'Teal'
    accent: 'Teal'
  font: false
  favicon: assets/images/favicon.png
  logo: 
    icon: "\uE80C"